"""empty message

Revision ID: 07edd21d9e8e
Revises: 3cf465063afd
Create Date: 2020-03-06 16:19:04.163017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07edd21d9e8e'
down_revision = '3cf465063afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'item_id')
    # ### end Alembic commands ###
