"""empty message

Revision ID: 0ffe62831e82
Revises: 289327fa2a1d
Create Date: 2020-02-26 15:22:00.638970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffe62831e82'
down_revision = '289327fa2a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('belong_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Team', ['belong_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'belong_team_id')
    # ### end Alembic commands ###
