"""empty message

Revision ID: 22ef4e8c8719
Revises: f3dbbc66955f
Create Date: 2020-02-27 10:39:55.776869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ef4e8c8719'
down_revision = 'f3dbbc66955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Team', 'Project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.drop_column('Team', 'project_id')
    # ### end Alembic commands ###
