"""empty message

Revision ID: 24f3223e754c
Revises: 3f9176e020d0
Create Date: 2020-02-27 10:50:19.481284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f3223e754c'
down_revision = '3f9176e020d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Item', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Item', 'User', ['executor_id'], ['id'])
    op.add_column('Note', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Note', 'Item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Note', type_='foreignkey')
    op.drop_column('Note', 'item_id')
    op.drop_constraint(None, 'Item', type_='foreignkey')
    op.drop_column('Item', 'executor_id')
    # ### end Alembic commands ###
