"""empty message

Revision ID: 265c6ba73c62
Revises: 24f3223e754c
Create Date: 2020-02-27 10:51:13.145683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265c6ba73c62'
down_revision = '24f3223e754c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note', sa.Column('writer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Note', 'User', ['writer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Note', type_='foreignkey')
    op.drop_column('Note', 'writer_id')
    # ### end Alembic commands ###
