"""empty message

Revision ID: 289327fa2a1d
Revises: 87fc16c5d2c0
Create Date: 2020-02-26 15:21:10.241598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '289327fa2a1d'
down_revision = '87fc16c5d2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('leader_id', sa.Integer(), nullable=True))
    op.drop_constraint('Team_ibfk_1', 'Team', type_='foreignkey')
    op.create_foreign_key(None, 'Team', 'User', ['leader_id'], ['id'])
    op.drop_column('Team', 'uid')
    op.drop_constraint('User_ibfk_1', 'User', type_='foreignkey')
    op.drop_column('User', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('team_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('User_ibfk_1', 'User', 'Team', ['team_id'], ['id'])
    op.add_column('Team', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.create_foreign_key('Team_ibfk_1', 'Team', 'User', ['uid'], ['id'])
    op.drop_column('Team', 'leader_id')
    # ### end Alembic commands ###
