"""empty message

Revision ID: 28a3cffecd20
Revises: 07edd21d9e8e
Create Date: 2020-03-06 16:35:25.940982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a3cffecd20'
down_revision = '07edd21d9e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Asset_ibfk_1', 'Asset', type_='foreignkey')
    op.create_foreign_key(None, 'Asset', 'User', ['uid'], ['id'])
    op.drop_constraint('LabTask_ibfk_1', 'LabTask', type_='foreignkey')
    op.create_foreign_key(None, 'LabTask', 'User', ['uid'], ['id'])
    op.add_column('User', sa.Column('enable', sa.Boolean(), nullable=True, comment='是否启用'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'enable')
    op.drop_constraint(None, 'LabTask', type_='foreignkey')
    op.create_foreign_key('LabTask_ibfk_1', 'LabTask', 'User', ['uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Asset', type_='foreignkey')
    op.create_foreign_key('Asset_ibfk_1', 'Asset', 'User', ['uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
