"""empty message

Revision ID: 35053d30d72a
Revises: b568f7687093
Create Date: 2020-03-04 21:24:56.107544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35053d30d72a'
down_revision = 'b568f7687093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('teammate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Team', 'User', ['teammate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.drop_column('Team', 'teammate_id')
    # ### end Alembic commands ###
