"""empty message

Revision ID: 3f9176e020d0
Revises: 22ef4e8c8719
Create Date: 2020-02-27 10:42:34.841319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9176e020d0'
down_revision = '22ef4e8c8719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Item', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Item', 'Project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Item', type_='foreignkey')
    op.drop_column('Item', 'project_id')
    # ### end Alembic commands ###
