"""empty message

Revision ID: 4a32584884c9
Revises: b1b18a167031
Create Date: 2020-02-17 16:47:05.019969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a32584884c9'
down_revision = 'b1b18a167031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'UserProfile', 'User', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserProfile', type_='foreignkey')
    op.drop_column('UserProfile', 'uid')
    # ### end Alembic commands ###
