"""empty message

Revision ID: 4a5760529685
Revises: 35053d30d72a
Create Date: 2020-03-04 21:53:13.720228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a5760529685'
down_revision = '35053d30d72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Team_ibfk_4', 'Team', type_='foreignkey')
    op.drop_column('Team', 'teammate_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('teammate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('Team_ibfk_4', 'Team', 'User', ['teammate_id'], ['id'])
    # ### end Alembic commands ###
