"""empty message

Revision ID: 87fc16c5d2c0
Revises: 56453176d49a
Create Date: 2020-02-26 15:12:40.667233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87fc16c5d2c0'
down_revision = '56453176d49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('uid', sa.Integer(), nullable=True))
    op.drop_constraint('Team_ibfk_1', 'Team', type_='foreignkey')
    op.create_foreign_key(None, 'Team', 'User', ['uid'], ['id'])
    op.drop_column('Team', 'user_id')
    op.add_column('User', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'team_id')
    op.add_column('Team', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.create_foreign_key('Team_ibfk_1', 'Team', 'User', ['user_id'], ['id'])
    op.drop_column('Team', 'uid')
    # ### end Alembic commands ###
