"""empty message

Revision ID: 9771d83c6f0a
Revises: f1d5d0a6fab9
Create Date: 2020-02-26 15:04:10.779759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9771d83c6f0a'
down_revision = 'f1d5d0a6fab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Team', 'User', ['uid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.drop_column('Team', 'uid')
    # ### end Alembic commands ###
