"""empty message

Revision ID: b1b18a167031
Revises: 45f1af0fbfa3
Create Date: 2020-02-17 15:57:54.494968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1b18a167031'
down_revision = '45f1af0fbfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('stu_num', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stu_num'),
    sa.UniqueConstraint('username')
    )
    op.create_table('UserProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.Integer(), nullable=True),
    sa.Column('github', sa.String(length=128), nullable=True),
    sa.Column('college', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('_class', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='user')
    op.drop_index('stu_num', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('stu_num', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('github_link', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('stu_num', 'user', ['stu_num'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_table('UserProfile')
    op.drop_table('User')
    # ### end Alembic commands ###
