"""empty message

Revision ID: b62011aa2462
Revises: e0f1a6843239
Create Date: 2020-03-02 14:47:50.013442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b62011aa2462'
down_revision = 'e0f1a6843239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Activity', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('Activity', sa.Column('execute_datetime', sa.DateTime(), nullable=True, comment='开始时间'))
    op.drop_column('Activity', 'datetime')
    op.add_column('LabTask', sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'))
    op.add_column('LabTask', sa.Column('execute_datetime', sa.DateTime(), nullable=True, comment='开始时间'))
    op.add_column('LabTask', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'LabTask', 'User', ['uid'], ['id'])
    op.add_column('Note', sa.Column('create_datetime', sa.DateTime(), nullable=True, comment='创建时间'))
    op.drop_column('Note', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note', sa.Column('datetime', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.drop_column('Note', 'create_datetime')
    op.drop_constraint(None, 'LabTask', type_='foreignkey')
    op.drop_column('LabTask', 'uid')
    op.drop_column('LabTask', 'execute_datetime')
    op.drop_column('LabTask', 'create_time')
    op.add_column('Activity', sa.Column('datetime', mysql.DATETIME(), nullable=True, comment='开始时间'))
    op.drop_column('Activity', 'execute_datetime')
    op.drop_column('Activity', 'create_time')
    # ### end Alembic commands ###
