"""empty message

Revision ID: b7e499536fea
Revises: 0ffe62831e82
Create Date: 2020-02-27 10:21:40.393011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e499536fea'
down_revision = '0ffe62831e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('manage_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Team', ['manage_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'manage_team_id')
    # ### end Alembic commands ###
