"""empty message

Revision ID: be888448c343
Revises: ce0f0522e07c
Create Date: 2020-02-27 10:25:48.194920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be888448c343'
down_revision = 'ce0f0522e07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Team_ibfk_2', 'Team', type_='foreignkey')
    op.drop_column('Team', 'teammate_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('teammate_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('Team_ibfk_2', 'Team', 'User', ['teammate_id'], ['id'])
    # ### end Alembic commands ###
