"""empty message

Revision ID: ce0f0522e07c
Revises: b7e499536fea
Create Date: 2020-02-27 10:23:04.893967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0f0522e07c'
down_revision = 'b7e499536fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Team', sa.Column('teammate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Team', 'User', ['teammate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Team', type_='foreignkey')
    op.drop_column('Team', 'teammate_id')
    # ### end Alembic commands ###
