"""empty message

Revision ID: d0def212d04d
Revises: 30b6afc52719
Create Date: 2020-02-18 14:23:55.934362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0def212d04d'
down_revision = '30b6afc52719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_lab_info', sa.Binary(), nullable=True, comment='修改实验室信息'),
    sa.Column('change_set', sa.Binary(), nullable=True, comment='修改座位'),
    sa.Column('verify_asset', sa.Binary(), nullable=True, comment='资产审核'),
    sa.Column('publish_lab_activity', sa.Binary(), nullable=True, comment='发布实验室活动'),
    sa.Column('manage_lab_task', sa.Binary(), nullable=True, comment='管理实验室事务'),
    sa.Column('change_team_info', sa.Binary(), nullable=True, comment='修改组信息'),
    sa.Column('publish_team_activity', sa.Binary(), nullable=True, comment='发布组活动'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('UserProfile', sa.Column('phone', sa.String(length=11), nullable=False))
    op.create_unique_constraint(None, 'UserProfile', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserProfile', type_='unique')
    op.drop_column('UserProfile', 'phone')
    op.drop_table('Permission')
    # ### end Alembic commands ###
