"""empty message

Revision ID: d534ab0651e1
Revises: 
Create Date: 2020-03-04 20:22:15.532083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd534ab0651e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='活动ID'),
    sa.Column('desc', sa.String(length=256), nullable=False, comment='活动内容'),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('execute_datetime', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=32), nullable=False, comment='项目名称'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='项目简介'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='终止时间'),
    sa.Column('status', sa.Enum('0', '1'), server_default='0', nullable=False, comment='状态'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=32), nullable=False, comment='小组名'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='小组简介'),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['Activity.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=64), nullable=False, comment='邮箱'),
    sa.Column('stu_num', sa.String(length=32), nullable=False, comment='学号'),
    sa.Column('password', sa.String(length=128), nullable=False, comment='密码'),
    sa.Column('role', sa.Enum('admin', 'monitor', 'student'), server_default='student', nullable=True),
    sa.Column('set_num', sa.Integer(), nullable=True, comment='座位号'),
    sa.Column('belong_team_id', sa.Integer(), nullable=True),
    sa.Column('manage_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['belong_team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['manage_team_id'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stu_num'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='资产ID'),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('asset_name', sa.String(length=32), nullable=False, comment='资产名称'),
    sa.Column('desc', sa.String(length=256), nullable=False, comment='详细信息'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='终止时间'),
    sa.Column('status', sa.Enum('0', '1', '2'), server_default='0', nullable=False, comment='状态'),
    sa.ForeignKeyConstraint(['uid'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.Enum('backlog', 'bug'), server_default='backlog', nullable=False, comment='类型'),
    sa.Column('desc', sa.String(length=256), nullable=True, comment='描述'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('status', sa.Enum('0', '1', '2', '3'), server_default='0', nullable=False, comment='状态'),
    sa.Column('priority', sa.Enum('0', '1', '2', '3'), server_default='0', nullable=False, comment='优先级'),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('LabTask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='事务ID'),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(length=32), nullable=False, comment='事务'),
    sa.Column('desc', sa.String(length=256), nullable=False, comment='事务详情'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('execute_datetime', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.ForeignKeyConstraint(['uid'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserPermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('manage_lab_student_profile', sa.Boolean(), nullable=True, comment='管理实验室学生信息'),
    sa.Column('manage_lab_task', sa.Boolean(), nullable=True, comment='管理实验室事务'),
    sa.Column('change_set', sa.Boolean(), nullable=True, comment='修改座位'),
    sa.Column('verify_asset', sa.Boolean(), nullable=True, comment='资产审核'),
    sa.Column('change_lab_info', sa.Boolean(), nullable=True, comment='修改实验室信息'),
    sa.Column('publish_lab_activity', sa.Boolean(), nullable=True, comment='发布实验室活动'),
    sa.Column('manage_lab_teams', sa.Boolean(), nullable=True, comment='管理小组'),
    sa.Column('change_team_info', sa.Boolean(), nullable=True, comment='修改组信息'),
    sa.Column('publish_team_activity', sa.Boolean(), nullable=True, comment='发布组活动'),
    sa.ForeignKeyConstraint(['uid'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('QQ', sa.String(length=11), nullable=True, comment='QQ'),
    sa.Column('wechat', sa.String(length=64), nullable=True, comment='微信'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='电话'),
    sa.Column('college', sa.String(length=32), nullable=False, comment='专业'),
    sa.Column('grade', sa.String(length=4), nullable=False, comment='年级'),
    sa.Column('_class', sa.String(length=4), nullable=False, comment='班级'),
    sa.ForeignKeyConstraint(['uid'], ['User.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('QQ'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('wechat')
    )
    op.create_table('Note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='记录ID'),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True, comment='记录内容'),
    sa.Column('create_datetime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Item.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Note')
    op.drop_table('UserProfile')
    op.drop_table('UserPermission')
    op.drop_table('LabTask')
    op.drop_table('Item')
    op.drop_table('Asset')
    op.drop_table('User')
    op.drop_table('Team')
    op.drop_table('Project')
    op.drop_table('Activity')
    # ### end Alembic commands ###
