"""empty message

Revision ID: e0f1a6843239
Revises: 779f5fe0051c
Create Date: 2020-03-02 11:03:35.626540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f1a6843239'
down_revision = '779f5fe0051c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LabTask',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='事务ID'),
    sa.Column('task_name', sa.String(length=32), nullable=False, comment='事务'),
    sa.Column('desc', sa.String(length=256), nullable=False, comment='事务详情'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LabTask')
    # ### end Alembic commands ###
