"""empty message

Revision ID: f1d5d0a6fab9
Revises: b67f6a9d5336
Create Date: 2020-02-26 14:49:05.112711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1d5d0a6fab9'
down_revision = 'b67f6a9d5336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Item_ibfk_1', 'Item', type_='foreignkey')
    op.drop_column('Item', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Item', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('Item_ibfk_1', 'Item', 'Project', ['project_id'], ['id'])
    # ### end Alembic commands ###
