"""empty message

Revision ID: fb24f1474028
Revises: d0def212d04d
Create Date: 2020-02-18 14:40:14.702166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb24f1474028'
down_revision = 'd0def212d04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserPermission',
    sa.Column('id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Permission')
    op.alter_column('User', 'email',
               existing_type=mysql.VARCHAR(length=128),
               comment='邮箱',
               existing_nullable=False)
    op.alter_column('User', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID',
               autoincrement=True)
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=128),
               comment='密码',
               existing_nullable=False)
    op.alter_column('User', 'stu_num',
               existing_type=mysql.VARCHAR(length=32),
               comment='学号',
               existing_nullable=False)
    op.alter_column('User', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('UserProfile', '_class',
               existing_type=mysql.VARCHAR(length=32),
               comment='班级',
               existing_nullable=False)
    op.alter_column('UserProfile', 'college',
               existing_type=mysql.VARCHAR(length=32),
               comment='专业',
               existing_nullable=False)
    op.alter_column('UserProfile', 'grade',
               existing_type=mysql.INTEGER(display_width=11),
               comment='年级',
               existing_nullable=False)
    op.alter_column('UserProfile', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment='手机号',
               existing_nullable=False)
    op.drop_column('UserProfile', 'id')
    op.drop_column('UserProfile', 'github')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('github', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('UserProfile', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.alter_column('UserProfile', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               comment=None,
               existing_comment='手机号',
               existing_nullable=False)
    op.alter_column('UserProfile', 'grade',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='年级',
               existing_nullable=False)
    op.alter_column('UserProfile', 'college',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='专业',
               existing_nullable=False)
    op.alter_column('UserProfile', '_class',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='班级',
               existing_nullable=False)
    op.alter_column('User', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('User', 'stu_num',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='学号',
               existing_nullable=False)
    op.alter_column('User', 'password',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
    op.alter_column('User', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户ID',
               autoincrement=True)
    op.alter_column('User', 'email',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
    op.create_table('Permission',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('change_lab_info', sa.BLOB(), nullable=True, comment='修改实验室信息'),
    sa.Column('change_set', sa.BLOB(), nullable=True, comment='修改座位'),
    sa.Column('verify_asset', sa.BLOB(), nullable=True, comment='资产审核'),
    sa.Column('publish_lab_activity', sa.BLOB(), nullable=True, comment='发布实验室活动'),
    sa.Column('manage_lab_task', sa.BLOB(), nullable=True, comment='管理实验室事务'),
    sa.Column('change_team_info', sa.BLOB(), nullable=True, comment='修改组信息'),
    sa.Column('publish_team_activity', sa.BLOB(), nullable=True, comment='发布组活动'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserPermission')
    # ### end Alembic commands ###
